sudo: false

language: node_js
node_js:
  - 10

before_install:
  - yarn add codecov.io coveralls

script:
  - yarn coverage

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
